server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  #Mariadb
  datasource:
    url: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwH1FqZ1SdLLml95t5OzNgT7AAAAuTCBtgYJKoZIhvcNAQcGoIGoMIGlAgEAMIGfBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHwCIvhnxcuo02acXAIBEIByDgapp5TYiqev3iAq9mzabK1qZ511Y99obDDHOG1Z8CSvdTuZ2AvSBDIMLLIHq/4Zb5G0mYKhaf2Mf+c6T6L+Eft24pZCja629MsnNgYcGscdSXGwDB9DVDPRb4pplK1xruZVNQB73C76Q+9cSt3gydvy'
    username: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwH5uVWg4U1DxUi9QUWBoRKTAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+XRP/1NdxxJ3dPRDAgEQgCMRZrqJnMlF2dknzWSikAa4JNa5YmFEBGIqe14uutEXkkV+bA=='
    password: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwG0SkyMOzk2KsOYKFgcgmG9AAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMs/d0AVYz9XOaJnMaAgEQgC1tH81ho3hJEML+MHqSNbZ9GVR/OieGrCoEJjn8oEfrwp5b/sZWuc4mLYfX/MY='
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html


youtube:
  base-url: https://www.googleapis.com/youtube/v3
ai:
  request-url : http://13.124.186.167:8000
  result-url: http://13.124.186.167:8000/results

aws:
  kms:
    keyId: 5e54b60b-abd3-45ff-8fed-53f147aac32c
    encryptionAlgorithm: "SYMMETRIC_DEFAULT"

jwt:
  secret: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwGc2jCSXOKLpXH9AbE+sM7pAAAArTCBqgYJKoZIhvcNAQcGoIGcMIGZAgEAMIGTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLskTbG+H1v//rmDdwIBEIBmQd79gXGyiXRnQ5XfFQU5rvPjTjLsxKIXApPpMmpOuugMVuoLDNmdxyqSZiQDOCcGOd7lT9y2MbY+ofvu8Wu9oc+Wzy8tcY2/BFF7DkDTjU8D2N+WFVWKf0IYD2GCPEiKxLN47nIx'

google:
  cloud-api-key: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwGURWRGPVtBAgK9o3Mc/Fy4AAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDsUdCsqDTR2V1PDwQIBEIBCZ+dPPIyWJh8S7gsIsxakpo8szjTbNXucmCW/i+LnXFwcDKrVW1QIeGmmQAkh4g8cFoLotJ6lrJenb2NA1+wht7hQ'
  client-id: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwG2yawOjNyeqfXayelhiJEDAAAAqzCBqAYJKoZIhvcNAQcGoIGaMIGXAgEAMIGRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDM25bhVmkHjntleeNAIBEIBkEiutxJ+N7kpWa/wH1gziipOG6AXZ/PmRI1mnD6vF8zZvwZhsKXzjsm7G9INvVqjwk+jRY1cTdldXs7J0ZCDurx56d7JC47PfjCPAFwW5GFjZiaaebBu+md1ahNH4nwpySHs9uQ=='


#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: info
