server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  datasource:
    url: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwH1FqZ1SdLLml95t5OzNgT7AAAAuTCBtgYJKoZIhvcNAQcGoIGoMIGlAgEAMIGfBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHwCIvhnxcuo02acXAIBEIByDgapp5TYiqev3iAq9mzabK1qZ511Y99obDDHOG1Z8CSvdTuZ2AvSBDIMLLIHq/4Zb5G0mYKhaf2Mf+c6T6L+Eft24pZCja629MsnNgYcGscdSXGwDB9DVDPRb4pplK1xruZVNQB73C76Q+9cSt3gydvy'
    username: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwH5uVWg4U1DxUi9QUWBoRKTAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+XRP/1NdxxJ3dPRDAgEQgCMRZrqJnMlF2dknzWSikAa4JNa5YmFEBGIqe14uutEXkkV+bA=='
    password: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwG0SkyMOzk2KsOYKFgcgmG9AAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMs/d0AVYz9XOaJnMaAgEQgC1tH81ho3hJEML+MHqSNbZ9GVR/OieGrCoEJjn8oEfrwp5b/sZWuc4mLYfX/MY='
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html


youtube:
  base-url: https://www.googleapis.com/youtube/v3
ai:
  request-url : http://13.124.186.167:8000
  result-url: http://13.124.186.167:8000/results

aws:
  kms:
    keyId: 5e54b60b-abd3-45ff-8fed-53f147aac32c
    encryptionAlgorithm: "SYMMETRIC_DEFAULT"

jwt:
  secret: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAH7vLPg8WH9EnVY8w2miixbAAAArTCBqgYJKoZIhvcNAQcGoIGcMIGZAgEAMIGTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLU1yqELVYSmkGGH+wIBEIBmIaeZzCy1NVtiMBgB+UP4m6r573GMnHrZD+gKaygwTKtKQ8bO6kRGmxK5oLlL7FUwQVfXyUsNH5Bl97UUibztt27L/ZZcEI+2M2Q6G036Kuo6pHeS+xrH3s+MJqGhyo7kdy0Dn4jd'

google:
  cloud-api-key: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAEoQJJDroLRhLf3/lRLpTy9AAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJpocrwECA/Qlw0riAIBEIBC82234hS32DU/WjS9tNySXFeCKY8iGra2TB5ayY53+06NsRkPKOWATKvtrm/FUZqnILBSkZT8dx0FZ/Ocw1NO3l+P'
  client-id: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAGe1mdXigBgHZxwI2CQ7StZAAAAqzCBqAYJKoZIhvcNAQcGoIGaMIGXAgEAMIGRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDK01letLDt4MQMOakQIBEIBkVachLXH71fMO5/1eLctnr7j3EnecJXj9WFTe2ineYIPc9kG3z5JYvaAM5np3TqD9t0XRGo2DEffcpyH9/GgEuzTxT2G3h+bAcOzHR9Hp/n93XcldtBO3oRrf/JlnXhzckKVu7Q=='


#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: info

logging:
  config: classpath:logback-dev.xml
