server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  #Mariadb
  datasource:
    url: ${url}
    username: ${username}
    password:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html

youtube:
  base-url: https://www.googleapis.com/youtube/v3
gpt:
  request-url : http://127.0.0.1:8000
  result-url: http://127.0.0.1:8000/results

#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: debug
