server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: prod
  datasource:
    url: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAHPAOSdm8wE+Cxuc6VCregSAAAAuDCBtQYJKoZIhvcNAQcGoIGnMIGkAgEAMIGeBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOICpwJ2bobFwfzHnAIBEIBx+qJKvcx4G3PygUMrLq0x2OGv+MiyHZvyhjUo9aqJxbJianSgGEbgw9P7S+Z9JCLAWbq20hya8Sj+eLHmqjPW5KQhkskJvUSsyY/Qvs2AN2doeeqvn4IJF/0uSk+WYG7iCLDr86NUluriP9JTw7vy/cI='
    username: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAHNXwhIi6Polmdvjvufy9+7AAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmFBB74e3Pj8wBb2MAgEQgCMfeeQOrFGu04lIbjWR5tA35b5cCNjntABp6dGlSC8GeHpDxw=='
    password: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAFp8hPMfVX5OOgyiGBs6kqWAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMN5+6ZH3/tAfiOT/XAgEQgCv/s/dY8SkjjlJobmMuy/+sQylwgYQcQtQ4ULfipHf/GkYH6t1kOlEWJVww'
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDB1011Dialect

youtube:
  base-url: https://www.googleapis.com/youtube/v3
ai:
  request-url : http://43.202.35.206:8000
  result-url: http://43.202.35.206:8000/results

aws:
  kms:
    keyId: 5e54b60b-abd3-45ff-8fed-53f147aac32c
    encryptionAlgorithm: "SYMMETRIC_DEFAULT"

jwt:
  secret: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAH7vLPg8WH9EnVY8w2miixbAAAArTCBqgYJKoZIhvcNAQcGoIGcMIGZAgEAMIGTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLU1yqELVYSmkGGH+wIBEIBmIaeZzCy1NVtiMBgB+UP4m6r573GMnHrZD+gKaygwTKtKQ8bO6kRGmxK5oLlL7FUwQVfXyUsNH5Bl97UUibztt27L/ZZcEI+2M2Q6G036Kuo6pHeS+xrH3s+MJqGhyo7kdy0Dn4jd'

google:
  cloud-api-key: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAEoQJJDroLRhLf3/lRLpTy9AAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJpocrwECA/Qlw0riAIBEIBC82234hS32DU/WjS9tNySXFeCKY8iGra2TB5ayY53+06NsRkPKOWATKvtrm/FUZqnILBSkZT8dx0FZ/Ocw1NO3l+P'
  client-id: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAGe1mdXigBgHZxwI2CQ7StZAAAAqzCBqAYJKoZIhvcNAQcGoIGaMIGXAgEAMIGRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDK01letLDt4MQMOakQIBEIBkVachLXH71fMO5/1eLctnr7j3EnecJXj9WFTe2ineYIPc9kG3z5JYvaAM5np3TqD9t0XRGo2DEffcpyH9/GgEuzTxT2G3h+bAcOzHR9Hp/n93XcldtBO3oRrf/JlnXhzckKVu7Q=='

#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: info


# logging.level:
#   root: warn
#   com.m9d:
#     web: warn
#     security: warn
#     boot: warn
#   com.hibernate:
#     SQL: warn
#   com.m9d.sroom: warn
logging:
  config: classpath:logback-prod.xml
