server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: prod
  datasource:
    url: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwFi1nFyEIdmEHfWArYDwqceAAAAujCBtwYJKoZIhvcNAQcGoIGpMIGmAgEAMIGgBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKQytm6GaBSm8yOStAIBEIBzg4s1gAn2/o+1LqFgDnRGZO33i9WwtbwgX2GBOYqgJaJu+WQWP0AeHhI0hh1GiwWvlJHEy/RdmSrmvVbeuSuoJXpbv48a4lDsVURU9j84Tp+RJ4bGBpI+SAXVeJq5pZCknGBjBvhd/x+roBsQkaiWQ6ftsA=='
    username: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwEzELYpV0RGum09fnpD8pCaAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM12R4qE4FCC1MWVk7AgEQgCN3ZWQKzdG+QL9ngq96lBdiR/z8mfJ4Jx+ys62ke7zTdn9nOw=='
    password: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwE3liqeSwLg6BMfyGzDrCr/AAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIS1y4wCTJvMdSLtnAgEQgCsrms+914SigtDKLExFvVY6SkdtfgD3njzhV56D3uKTrdM7r7RyzgUIh4Fb'
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html

youtube:
  base-url: https://www.googleapis.com/youtube/v3
ai:
  request-url : http://43.200.123.116:8000
  result-url: http://43.200.123.116:8000/results

aws:
  kms:
    keyId: 5e54b60b-abd3-45ff-8fed-53f147aac32c
    encryptionAlgorithm: "SYMMETRIC_DEFAULT"

jwt:
  secret: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwGc2jCSXOKLpXH9AbE+sM7pAAAArTCBqgYJKoZIhvcNAQcGoIGcMIGZAgEAMIGTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLskTbG+H1v//rmDdwIBEIBmQd79gXGyiXRnQ5XfFQU5rvPjTjLsxKIXApPpMmpOuugMVuoLDNmdxyqSZiQDOCcGOd7lT9y2MbY+ofvu8Wu9oc+Wzy8tcY2/BFF7DkDTjU8D2N+WFVWKf0IYD2GCPEiKxLN47nIx'

google:
  cloud-api-key: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwFCVC6YxozYAoEe4/iQt8bZAAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFg4wlwaWYQ6N7g3eAIBEIBCHzisPm13k8ItUCt/iUcEdCWZokpg/aN45VTQDzqJ2dx6Mry6ROln7QmYsm8apTrxmlBZSOiQy3B7Sz2h4lLHzg+D'
  client-id: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwG2yawOjNyeqfXayelhiJEDAAAAqzCBqAYJKoZIhvcNAQcGoIGaMIGXAgEAMIGRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDM25bhVmkHjntleeNAIBEIBkEiutxJ+N7kpWa/wH1gziipOG6AXZ/PmRI1mnD6vF8zZvwZhsKXzjsm7G9INvVqjwk+jRY1cTdldXs7J0ZCDurx56d7JC47PfjCPAFwW5GFjZiaaebBu+md1ahNH4nwpySHs9uQ=='

#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: info


# logging.level:
#   root: warn
#   com.m9d:
#     web: warn
#     security: warn
#     boot: warn
#   com.hibernate:
#     SQL: warn
#   com.m9d.sroom: warn
logging:
  config: classpath:logback-prod.xml
