server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: local
  datasource:
    url: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwFgKaFUhb2270ABK3DnbJmdAAAAgTB/BgkqhkiG9w0BBwagcjBwAgEAMGsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM63tWuWz+AGNzEt6CAgEQgD5h5ko0Btj+wakVyWki4moxiVNxCaVCO85TfjW4r8/r7w1oH3SGTLhpIUMA4vsMpHpbEHU86oTA51CwM8UZMQ=='
    username: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwEQ6p1YRsmHhzcx/mDyocEGAAAAYjBgBgkqhkiG9w0BBwagUzBRAgEAMEwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuy+zBtDQjkRuQM1BAgEQgB/z78W4hPAeVK23Uc53bCNO4eLxubnJDFr7h2LqglLf'
    password:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html

youtube:
  base-url: https://www.googleapis.com/youtube/v3
ai:
  request-url : http://127.0.0.1:8000
  result-url: http://127.0.0.1:8000/results

aws:
  kms:
    keyId: 5e54b60b-abd3-45ff-8fed-53f147aac32c
    encryptionAlgorithm: "SYMMETRIC_DEFAULT"

jwt:
  secret: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwGc2jCSXOKLpXH9AbE+sM7pAAAArTCBqgYJKoZIhvcNAQcGoIGcMIGZAgEAMIGTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLskTbG+H1v//rmDdwIBEIBmQd79gXGyiXRnQ5XfFQU5rvPjTjLsxKIXApPpMmpOuugMVuoLDNmdxyqSZiQDOCcGOd7lT9y2MbY+ofvu8Wu9oc+Wzy8tcY2/BFF7DkDTjU8D2N+WFVWKf0IYD2GCPEiKxLN47nIx'

google:
  cloud-api-key-1: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwHRoo8cXEo8h1DtHJaaRcF0AAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDH1Le6q//ORaQusuWAIBEIBCzcGZ7iHDq2bPiluU8ty4LMlGRLnAHtfCp0D6KZk3NXic4hx1QONzq6VReNLQrHEvHS7xl08Qgt3pKrnLhDjHimFE'
  cloud-api-key-2: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwGEd53pH0UxByqW6IxKokUbAAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJ+ntZL9x1kW/sj+eAIBEIBCxfArm1TkNWEltEWtGgo/D1YwJdEEZEsP7VA2NDbBf1AaD8oV1H+bpFGJb8PPlM0kKWZnIbq4MRuAE3dMZrE7oAF4'
  cloud-api-key-3: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwEk53nHJvGE0vXNMTR2KBGUAAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHAWWjozlaHazSSz3AIBEIBCOGbtSkzMnW+WK2M6FlFvWkW6NAx12nrBaH+cW6hg3ijQO4HcUHdFZyPM/rWTeKV1lXL6NiN/lW/bc+PH6YWR2Ak8'
  cloud-api-key-4: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwEO3pQI6UGU6OGNQb7MmwlJAAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDO8sVfl8XCtepNrtPgIBEIBCv61NMRffK5AXqB8OxPtdZvJdmTJj1S6IwKcGkCdDBZc7XJntwH6Ggwr+1suxCc5skhQ+GnaoeTdifmi0vaDfbw7K'
  client-id: '{cipher}AQICAHiJ3G9QsgoCm+bUcAPegP56f6tkFnNiijhZN1RaChF0LwG2yawOjNyeqfXayelhiJEDAAAAqzCBqAYJKoZIhvcNAQcGoIGaMIGXAgEAMIGRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDM25bhVmkHjntleeNAIBEIBkEiutxJ+N7kpWa/wH1gziipOG6AXZ/PmRI1mnD6vF8zZvwZhsKXzjsm7G9INvVqjwk+jRY1cTdldXs7J0ZCDurx56d7JC47PfjCPAFwW5GFjZiaaebBu+md1ahNH4nwpySHs9uQ=='

#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: debug
logging:
  config: classpath:logback-local.xml