server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  datasource:
    url: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAHWpHBhzB+J7tcOrudb96vHAAAAvTCBugYJKoZIhvcNAQcGoIGsMIGpAgEAMIGjBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLwcTYdyDLFUG1kGsAIBEIB26Lrzr2RbYYNSo5DStoEkTdSolHsNr8WtAB7nQOkmVDZrGStu0Sb3KH9HjfBhgvwLVgtUh1Suk+9fFRIfZgKC7VEyRQB+vrdKmILJRf20WYtUg0VKs8TJ5L3AVOYnuPtSf87hhUtzexYAfLhrRUHY8xVlu4bV6A=='
    username: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAGWpwtXmWvsQVAseYqGO72hAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMipQ4aEXUYC7IIJpcAgEQgCPuBK6EIKV7Jd4Qb95oTx3qkEWWdHU6KsVuCAEAYp5wjee88A=='
    password: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAFFXqObvvMFcqtUTmOTr955AAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4QZGvOKuZLbQe6zsAgEQgC2AckJVEX/a1XTgS0fo2Sps8sQM3HHzkuzrvVmeXd56wF+1MPZt6H10pvklDR8='
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500
  mvc:
    view:
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDB1011Dialect


youtube:
  base-url: https://www.googleapis.com/youtube/v3
ai:
  request-url : http://52.78.250.177:8000
  result-url: http://52.78.250.177:8000/results

aws:
  kms:
    keyId: 5e54b60b-abd3-45ff-8fed-53f147aac32c
    encryptionAlgorithm: "SYMMETRIC_DEFAULT"

jwt:
  secret: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAH7vLPg8WH9EnVY8w2miixbAAAArTCBqgYJKoZIhvcNAQcGoIGcMIGZAgEAMIGTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLU1yqELVYSmkGGH+wIBEIBmIaeZzCy1NVtiMBgB+UP4m6r573GMnHrZD+gKaygwTKtKQ8bO6kRGmxK5oLlL7FUwQVfXyUsNH5Bl97UUibztt27L/ZZcEI+2M2Q6G036Kuo6pHeS+xrH3s+MJqGhyo7kdy0Dn4jd'

google:
  cloud-api-key: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAEoQJJDroLRhLf3/lRLpTy9AAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJpocrwECA/Qlw0riAIBEIBC82234hS32DU/WjS9tNySXFeCKY8iGra2TB5ayY53+06NsRkPKOWATKvtrm/FUZqnILBSkZT8dx0FZ/Ocw1NO3l+P'
  client-id: '{cipher}AQICAHiGKnLyWc0ZUra/HszDAQiLV/XwHEAQgwJdRl7/UiE1gAGe1mdXigBgHZxwI2CQ7StZAAAAqzCBqAYJKoZIhvcNAQcGoIGaMIGXAgEAMIGRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDK01letLDt4MQMOakQIBEIBkVachLXH71fMO5/1eLctnr7j3EnecJXj9WFTe2ineYIPc9kG3z5JYvaAM5np3TqD9t0XRGo2DEffcpyH9/GgEuzTxT2G3h+bAcOzHR9Hp/n93XcldtBO3oRrf/JlnXhzckKVu7Q=='


#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  com.m9d:
    web: info
    security: info
    boot: info
  com.hibernate:
    SQL: debug
  com.m9d.sroom: info

logging:
  config: classpath:logback-dev.xml
