GET https://www.googleapis.com/youtube/v3/search?part=id,snippet&fields=nextPageToken,prevPageToken,pageInfo,items(id,snippet(title,channelTitle,thumbnails,description,publishTime))&maxResults=10&key=AIzaSyDnRkziwFWZfRDLhq7xPf14tHXsFri-ONg&q=css
Accept: application/json

###
GET http://localhost:8080/api/lectures?keyword=
Accept: application/json

###
GET http://localhost:8080/lectures?keyword=css?&limit=5
Accept: application/json

###
GET http://localhost:8080/api/lectures?keyword=네트워크&limit=4
Accept: application/json

###
GET http://localhost:8080/lectures?keyword=css&prevPageToken=CAUQAQ
Accept: application/json